# This is a basic workflow that is manually triggered
name: Instance Scan Point

on:
  workflow_dispatch:    
    inputs:
      name:        
        description: 'Testing the Instance point scan'        
        default: 'Scan Point'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  scan:
    name: Scanning Instances    
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: ServiceNow CI/CD Instance Scan
        uses: ./
        id: scan
        with:
          scantype: point  # full, point, suite_combo, suite_scoped, suite_update
          targetTable: 289d1622a5300110c0a0e1db2cdc9566 # sys_properties extends to sys_metadata
          targetSysId: c0b684d48713001001c8de05b7cb0b51 # Table Check - Increased number of unsuccessful password reset attempts
          # comboSysId: <combo_sys_id>          
          # suiteSysId: <suite_sys_id>
          # appScopeSysIds: <app_scope_sys_ids_comma_separated>
          # updateSetSysIds: <update_set_sys_ids_comma_separated>          
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowScanInstance: ${{ secrets.NOW_SCAN_INSTANCE }}
