# This is a basic workflow that is manually triggered
name: Instance Scan `date`

on:
  workflow_dispatch:    
    inputs:
      name:        
        description: 'Testing the Instance scan'        
        default: 'Scan'        
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  scan:
    name: Scanning Instances    
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: ServiceNow CI/CD Instance Scan
        uses: ./
        id: scan
        with:
          scantype: suite_scoped  # full, point, suite_combo, suite_scoped, suite_update
          # targetTable: <target_table>
          # targetSysId: <target_sys_id>
          # comboSysId: <combo_sys_id>
          suiteSysId: e336165f87c60510d941a9f83cbb3517
          appScopeSysIds: global
          updateSetSysIds: 4831eaa2a5740110c0a0e1db2cdc955b
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowScanInstance: ${{ secrets.NOW_SCAN_INSTANCE }}
